version = 1

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Eason-commits/1"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"